POST http://localhost:3000/contributor HTTP/1.1
content-type: application/json

{
    "skills": "truck driving", 
    "interests": "climate change", 
    "email": "faizah.sayyid@gmail.com",
    "star_sign": "Cancer"
}

###

GET http://localhost:3000/contributor/project/6d8ad50d-26aa-4af1-82d6-27b8f7522de9 HTTP/1.1