POST http://localhost:3000/contributor HTTP/1.1
content-type: application/json

{
    "skills": "truck driving", 
    "interests": "climate change", 
    "email": "faizah.sayyid@gmail.com",
    "star_sign": "Cancer"
}

###

GET http://localhost:3000/contributor/recommend/df7dd820-3fd3-46aa-8e45-2bce18ca48c5 HTTP/1.1